alias gdrive='google-drive-ocamlfuse -label mine ~/gdrive'
alias standrive='google-drive-ocamlfuse standrive'
alias no-gdrive='fusermount -u gdrive'
alias no-standrive='fusermount -u standrive'
alias s='cat ~/sc'
alias regenerate='sudo apt-get update && sudo apt-get upgrade'
alias get='sudo apt-get install'
alias moc='padsp mocp'
alias phd='vim -S /home/aj/phd/.phdsession.vim'
alias agenda='cp /home/aj/Documents/sallies/.template.mkd /home/aj/Documents/sallies/meeting_$(date +%Y-%m-%d).mkd && pandoc --smart --template=/home/aj/.vim/pandoc-templates/ajpdf --latex-engine=xelatex /home/aj/Documents/sallies/meeting_$(date +%Y-%m-%d).mkd -o /home/aj/Documents/sallies/meeting_$(date +%Y-%m-%d).pdf && evince /home/aj/Documents/sallies/meeting_$(date +%Y-%m-%d).pdf 2> /dev/null & vim /home/aj/Documents/sallies/meeting_$(date +%Y-%m-%d).mkd'
